type User @table {
  username: String!
  createdAt: Timestamp!
  email: String
  firstName: String
  lastName: String
}

type Medication @table {
  user: User!
  name: String!
  dosage: String!
  frequency: String!
  startDate: Date!
  createdAt: Timestamp!
  instructions: String
  endDate: Date
}

type Dose @table {
  user: User!
  medication: Medication!
  scheduledTime: Timestamp!
  createdAt: Timestamp!
  actualTakenTime: Timestamp
  notes: String
  taken: Boolean
}

type Reminder @table {
  user: User!
  medication: Medication!
  reminderTime: Timestamp!
  enabled: Boolean!
  createdAt: Timestamp!
  notificationSound: String
}